### ISSUE TITLE
abouheif.moran() plots (and output?) differ from earlier versions

### ISSUE THREAD

**Issue by steffilazerte** [aursiber/adephylo#8]
I've been trying to interpret the output of the abouheif.moran() tests and one of the problems I'm running into is that the output seems to have changed between versions. 

For example, the vignette from v.1.1-6 has the following output:[adephylo-aboutest-v1.1-6.pdf](https://github.com/thibautjombart/adephylo/files/1373397/adephylo-aboutest-v1.1-6.pdf). This figure shows a nice histogram showing the distribution of expected and observed values.

However, the current vignette (v1.1-10) shows the following figure: 
[adephylo-aboutest-v1.1-10.pdf](https://github.com/thibautjombart/adephylo/files/1373398/adephylo-aboutest-v1.1-10.pdf). Just an observation and a block. 

I'm wondering if this is related to the output of the Abouheif test which seems to have Infinite Std errors and either significant or non significant values (either 1.000 or 0.001):

```data(ungulates)
tre <- read.tree(text=ungulates$tre)
x <- phylo4d(tre, ungulates$tab)

Found more than one class "phylo" in cache; using the first, from namespace 'RNeXML'
Also defined by ‘treeio’

## Abouheif's tests for each trait
myTests <- abouheif.moran(x)
myTests

class: krandtest lightkrandtest 
Monte-Carlo tests
Call: as.krandtest(sim = matrix(res$result, ncol = nvar, byrow = TRUE), 
    obs = res$obs, alter = alter, names = test.names)

Number of tests:   4 

Adjustment method for multiple comparisons:   none 
Permutation number:   999 
  Test       Obs Std.Obs   Alter Pvalue
1 afbw 0.1653920    -Inf greater  1.000
2  mnw 0.3681410     Inf greater  0.001
3  fnw 0.3843272     Inf greater  0.001
4   ls 0.3002425     Inf greater  0.001

```

Have I misunderstood something, or is there a bug?

**Comment by sdray** [comment]
Hi Steffi,

indeed, there was a bug introduced in C code. I just correct it and push the new version on GitHub. Thanks a lot for your feedback.

Cheers

**Comment by steffilazerte** [comment]
Fantastic! I can confirm that it matches the abouheif.moran() output from v1.1-6 for my analyses. Thanks for the quick turn around.
